version: "3.8"

networks:
  mynetwork:

services:


  dynamodb:
    image: amazon/dynamodb-local
    networks:
      - mynetwork
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]
  
  postgres:
    image: postgres:latest
    networks:
      - mynetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=final
    ports:
      - "5432:5432"

  frontend:
    build: ./src/frontend
    networks:
      - mynetwork
    environment:
      - PORT=8080
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:7777
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CART_SERVICE_ADDR=cartservice:7070
      - CHECKOUT_SERVICE_ADDR=checkoutservice:9898
      - SHIPPING_SERVICE_ADDR=shippingservice:50052
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - EMAIL_SERVICE_ADDR=emailservice:9090
      - AD_SERVICE_ADDR=adservice:9555
      - ENV_PLATFORM=aws
      - SHOPPING_ASSISTANT_SERVICE_ADDR=cartservice:7070

  redis-server:
    image: redis:alpine
    networks:
      - mynetwork
    ports:
      - "6379:6379"

  adservice:
    build : ./src/adservice
    networks:
      - mynetwork
    environment:
      - PORT=9555

  cartservice:
    build: ./src/cartservice/src
    networks:
      - mynetwork
    environment:
      - REDIS_ADDR=redis-server:6379

  checkoutservice:
    build: ./src/checkoutservice
    networks:
      - mynetwork
    environment:
      - PORT=9898
      - ENABLE_TRACING=0
      - ENABLE_PROFILER=0
      - SHIPPING_SERVICE_ADDR=shippingservice:50052
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - EMAIL_SERVICE_ADDR=emailservice:9090
      - ENV_PLATFORM=aws

      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=final 

      - TABLE_ORDERS=orders
      - TABLE_ORDER_ITEMS=order_items
      - TABLE_ORDER_PAYMENTS=order_payments
      - TABLE_ORDER_SHIPMENTS=order_shipments

  currencyservice:
    build: ./src/currencyservice
    networks:
      - mynetwork
    environment:
      - PORT=7000
      - DISABLE_PROFILER=true 
      - DISABLE_TRACING=true 

  emailservice:
    build: ./src/emailservice
    networks:
      - mynetwork
    environment:
      - PORT=9090
      - DISABLE_PROFILER=true 
      - DISABLE_TRACING=true

  paymentservice:
    build: ./src/paymentservice
    networks:
      - mynetwork
    environment:
      - PORT=50051
      - DISABLE_PROFILER=true
      - DISABLE_TRACER=true 
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=final
      - POSTGRES_TABLE=payment 

  productcatalogservice:
    build: ./src/productcatalogservice
    networks:
      - mynetwork
    environment:
      - PORT=3550
      - DISABLE_PROFILER=1
      - DISABLE_TRACER=1 
      - DYNAMODB_TABLE_NAME=Products
      - DYNAMODB_LOCAL_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy 

  recommendationservice:
    build: ./src/recommendationservice
    networks:
      - mynetwork
    environment:
      - PORT=7777
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - ENABLE_PROFILER=false 
      - DISABLE_TRACER=true

  shippingservice:
    build: ./src/shippingservice
    networks:
      - mynetwork
    environment:
      - PORT=50052
      - DISABLE_PROFILER=false
      - ENABLE_TRACING=false
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=final
      - POSTGRES_TABLE=tracking 
